Карточка акций
alyonastartseva/kata-dns-store-2 pull request #11
Opened 2023-11-04 14:12 UTC by DaryaPyatina

2023-11-04 20:03 UTC, fixitalredy approved these changes

2023-11-06 19:05 UTC, valentimeYAR approved these changes

2023-11-07 07:37 UTC, SergeyChudinov approved these changes

2023-11-07 09:00 UTC, ClassyNik2 commented on src/components/ActionCard/ActionCard.module.scss
> +  color: #7c4cff;
Все цвета в переменные

2023-11-07 09:01 UTC, ClassyNik2 commented on src/components/ActionCard/ActionCard.tsx
> +interface IProps {
Вынеси в types если используешь обозначение IProps и назови уникально

2023-11-07 09:17 UTC, ClassyNik2 approved these changes

2023-11-07 09:38 UTC, DaryaPyatina commented on src/components/ActionCard/ActionCard.tsx
> +interface IProps {
Компонентов может быть много, и намного удобнее, чтоб они были рядом с компонентой, это стандартный подход

2023-11-07 22:45 UTC, alyonastartseva requested changes

2023-11-07 22:45 UTC, alyonastartseva commented on .prettierrc
> +  "printWidth": 80,
почему конфиг претира поменялся?

2023-11-07 22:46 UTC, alyonastartseva approved these changes

2023-11-08 08:42 UTC, DaryaPyatina commented on .prettierrc
> +  "printWidth": 80,
когда создавала несколько компонентов, всё растягивалось в длину и из-за этого было неудобно, прочитала, что от 80 до 100 будет нагляднее

2023-11-08 15:52 UTC, merged