Feature/header
alyonastartseva/kata-dns-store-2 pull request #6
Opened 2023-11-02 18:21 UTC by fixitalredy

Header

2023-11-02 19:29 UTC, ClassyNik2 approved these changes

2023-11-02 19:31 UTC, valentimeYAR reviewed
Я думал, что мы будем использовать модульные стили, а не бэм

2023-11-02 20:59 UTC, fixitalredy commented
> Я думал, что мы будем использовать модульные стили, а не бэм

переписал

2023-11-03 15:30 UTC, SergeyChudinov approved these changes

2023-11-07 08:48 UTC, ClassyNik2 commented on src/components/Header/Header.module.scss
> +    color: #8c8c8c !important;
По хорошему убрать important

2023-11-07 08:49 UTC, ClassyNik2 commented on src/styles/vars.scss
> +$orange-lighter: #ffa319;
Не уверен что сокращать переменные даже если они читаемые  хорошая идея, @alyonastartseva поправь если не прав

2023-11-07 08:51 UTC, ClassyNik2 commented on src/components/Search/antD.scss
> +      0 0 0 1px rgba(0, 0, 0, 0.04),
Раз этот  box shadow применяется несколько раз может в переменную вынести?

2023-11-07 08:52 UTC, ClassyNik2 commented on src/components/Header/Header.tsx
> +              </div>
Может быть меню через map лучше сделать?

2023-11-07 09:18 UTC, ClassyNik2 approved these changes

2023-11-07 13:53 UTC, alyonastartseva requested changes

2023-11-07 13:53 UTC, alyonastartseva commented on src/App.tsx
> +      <Header />
comment

2023-11-07 21:54 UTC, alyonastartseva commented on src/styles/vars.scss
> +$orange-lighter: #ffa319;
bg - норм)
txt - спорно

2023-11-07 22:10 UTC, alyonastartseva requested changes

2023-11-07 22:11 UTC, fixitalredy commented on src/components/Header/Header.module.scss
> +  /*font-family: $font*/
я оставил для подключения шрифта, чтоб не забыть....

2023-11-08 22:14 UTC, alyonastartseva requested changes

2023-11-08 22:14 UTC, alyonastartseva commented on src/App.tsx
> +      <Layout />
По-хорошему, App должен возвращать роуты

а Layout уже использовать в этих роутах (hint: посмотри в сторону Element и Children при конфигурации роутов)

2023-11-08 22:14 UTC, alyonastartseva commented on src/components/Header/Header.tsx
> +import Search from '../Search/Search'
`import Search from '../Search`

2023-11-09 13:29 UTC, alyonastartseva approved these changes

2023-11-09 13:29 UTC, alyonastartseva commented on src/App.tsx
> +import Layout from './components/Layout/Layout'
поправь, плиз, импорту Layout и HomePage (и везде проверь, плиз)

2023-11-09 14:24 UTC, merged