feature/4-stores_page)
alyonastartseva/kata-dns-store-2 pull request #7
Opened 2023-11-03 08:45 UTC by BorisKolmakov

Страничка "Магазины". Оставил пустые дивы под список магазинов и карту. Кастомный скролл для списка магазинов. Изменил стили чекбоксов antd. Абсолютные импорты присутствуют

2023-11-03 10:00 UTC, ClassyNik2 requested changes

2023-11-03 10:00 UTC, ClassyNik2 commented on .eslintrc.json
> +    "import/no-unresolved": "off",
Зачем отключена проверка модулей?

2023-11-03 10:00 UTC, ClassyNik2 commented on src/components/StoresPage/StoresPage.module.scss
> +@import "src/styles/vars.scss";
includes Несет в себе все остальные импорты в том числе vars. измени импорт

2023-11-03 10:00 UTC, ClassyNik2 commented on src/components/StoresPage/StoresPage.module.scss
> +@media (min-width: 992px) and (max-width: 1199px) {
Может стоит переписать все медиа запросы в mixins?

2023-11-03 10:00 UTC, ClassyNik2 commented on src/components/StoresPage/StoresPage.tsx
> +import s from 'src/components/StoresPage/StoresPage.module.scss'
Было бы неплохо назвать вместо s classes

2023-11-03 10:00 UTC, ClassyNik2 commented on src/main.tsx
> +import 'src/styles/index.scss'
index scss и в main и в app лежит

2023-11-03 10:00 UTC, ClassyNik2 commented on src/styles/index.scss
> +@import url('https://fonts.googleapis.com/css2?family=PT+Sans:wght@400;700&display=swap');
fonts подключены в отдельной таске, вытащи оттуда

2023-11-07 07:30 UTC, SergeyChudinov approved these changes

2023-11-07 09:28 UTC, ClassyNik2 approved these changes

2023-11-07 21:51 UTC, alyonastartseva requested changes

2023-11-07 21:51 UTC, alyonastartseva commented on src/components/StoresPage/antD.scss
> +.ant-checkbox-checked .ant-checkbox-inner {
такие кастомные чекбоксы будут только на странице магазинов?

если могут/будут использоваться в других частях приложения, то лучше вынести на shared-слой - в папочку styles

2023-11-07 21:51 UTC, alyonastartseva commented on src/router/AppRouter.tsx
> +      <Route path={'/'} element={<StoresPage />} />
в качестве новой альтернативы можно посмотреть в сторону хука useRoutes

2023-11-07 21:51 UTC, alyonastartseva commented on src/styles/index.scss
> +  background: #f7f7f7;
для App лучше не применять никакую логику "раскраски" - это всё делать на страницах-компонентах

2023-11-08 22:02 UTC, alyonastartseva approved these changes

2023-11-09 03:22 UTC, merged